import type { Metadata } from "next";
import "./globals.css";
import Nav from "./layout/header/Nav";
import Footer from "./layout/footer/Footer";

export const metadata: Metadata = {
  title: "Finbox",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
